USE biblioteca_db;

CREATE TABLE IF NOT EXISTS Usuario (
  ID_Usuario INT PRIMARY KEY AUTO_INCREMENT,
  Nome VARCHAR(150) NOT NULL,
  Email VARCHAR(150) NOT NULL UNIQUE,
  Telefone VARCHAR(20),
  Tipo VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Categoria (
  ID_Categoria INT PRIMARY KEY AUTO_INCREMENT,
  Nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Livro (
  ID_Livro INT PRIMARY KEY AUTO_INCREMENT,
  Titulo VARCHAR(250) NOT NULL,
  ISBN VARCHAR(20) UNIQUE,
  Editora VARCHAR(100),
  Ano_Publicacao SMALLINT,
  Qtd_Exemplares INT NOT NULL DEFAULT 1,
  ID_Categoria INT NOT NULL,
  FOREIGN KEY (ID_Categoria) REFERENCES Categoria(ID_Categoria)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS Emprestimo (
  ID_Emprestimo INT PRIMARY KEY AUTO_INCREMENT,
  ID_Usuario INT NOT NULL,
  ID_Livro INT NOT NULL,
  Data_Emprestimo DATE NOT NULL,
  Data_Devolucao DATE NOT NULL,
  Data_Devolucao_Real DATE,
  Multa DECIMAL(8,2),
  FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  FOREIGN KEY (ID_Livro) REFERENCES Livro(ID_Livro)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS Avaliacao (
  ID_Avaliacao INT PRIMARY KEY AUTO_INCREMENT,
  ID_Usuario INT NOT NULL,
  ID_Livro INT NOT NULL,
  Nota SMALLINT NOT NULL,
  Comentario TEXT,
  Data_Avaliacao DATE,
  FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  FOREIGN KEY (ID_Livro) REFERENCES Livro(ID_Livro)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);
